### ISSUE TITLE
Broken Interaction: Project E

### ISSUE THREAD

**Issue by Zsashas** [blay09/TCInventoryScanning#10]
Scanning items stored as concepts in a Project E Transmutation Table (or Tablet) reveals the aspects of the item, but does not give points for them. Either have them give points, or disallow scanning, like you do for the Crafting Table output and NEI and such, if possible.

**Comment by BlayTheNinth** [comment]
Closing since 1.7.10 isn't receiving further updates, if the issue persists within 1.10.2 feel free to re-open.
