### ISSUE TITLE
ProjectE / Applied Energistics - Tablet / Table / AE system scanning (suggestion)

### ISSUE THREAD

**Issue by EmergentCapulin** [blay09/TCInventoryScanning#17]
First off, thanks for updating this to 1.12 - it is fantastic to go inventory scanning again.

I was just curious if it might be possible to include inventory scanning for Project E Tablets / Tables and AE2 type inventory networks.  As Thaumcraft in general allows us to do a whole chest worth of scanning from the outside - I would like to personally use this to be able to go inside of those mega inventories and scan in there. 

Currently AE2 doesn't have any kind of "scanning" announcement pop up.  Similarly, no "points" or popups are rewarded when hovering over unknown objects for a time. 

Project E however begins scanning - but doesn't give the announcement of "points" or any aspects.  So, your mod is trying to scan things in Project E, but something blocks or it just doesn't know what to do at X point in time.

Thanks again.

Capulin

**Comment by EmergentCapulin** [comment]
Was looking through the "closed" logs and saw the "won't fix" by the post about AE2.  I apologize if this is not a priority as didn't see the other previous posts.

**Comment by BlayTheNinth** [comment]
Closing since there won't be any more releases unless there ever comes a modern version Thaumcraft with need for this.
