### ISSUE TITLE
Mod in-game is called "Thaumcrafft Inventory Scanning" instead of Thaumcraft

### ISSUE THREAD

**Issue by aaronhowser1** [blay09/TCInventoryScanning#23]
![image](https://user-images.githubusercontent.com/15698722/95161794-ad933b80-0769-11eb-9240-a73206b99fe0.png)

 ThaumicInventoryScanning_1.12.2-2.0.10.jar

**Comment by BlayTheNinth** [comment]
Closing since there won't be any more releases unless there ever comes a modern version Thaumcraft with need for this.
