### ISSUE TITLE
Alert description error

### ISSUE THREAD

**Issue by Intezium** [blay09/TCInventoryScanning#24]
1) Install Thaumic Inventory Scanning (**only** client side)
2) Join to the server without Thaumic Inventory Scanning
![image](https://user-images.githubusercontent.com/20191322/114994263-45a27800-9ea5-11eb-975e-55f6295b5f2b.png)

Minecraft : `1.7.10`
Thaumic Inventory Scanning: `1.0.11`

**Comment by BlayTheNinth** [comment]
This is fixed in later versions, 1.7.10 is no longer supported.
