### ISSUE TITLE
Better explanation

### ISSUE THREAD

**Issue by blarghhh** [blay09/TCInventoryScanning#3]
i think you should reword this section slightly differently.

"Hover over an item in an inventory while holding a Thaumometer in order to scan that item"

i think it should read

"Scan while Thaumometer is on the cursor to scan" or something like that.

and it doesn't work with the ae terminal.

**Comment by blay09** [comment]
I agree on the "on the cursor" part, but the rest of your sentence is more confusing than it is now. "Scan to scan"?

Also yes, it does not work in the AE Terminal.

**Comment by blarghhh** [comment]
Yeah. My main point is the "on the cursor" but didn't put it across well.
