### ISSUE TITLE
Scanning certain items causing crash [1.0.3] 

### ISSUE THREAD

**Issue by dirtyfargo** [blay09/TCInventoryScanning#4]
When I scan a Shiny ingot from Thermal Foundation, with only Thaumcraft, Baubles, CoFHCore, and TC Inventory Scanning installed with it, my game is exited to the main menu with this in the client log (no actual crash-report):  https://gist.github.com/dirtyfargo/1b269f29aba3c96062ad
When re-logging into the world, the Thaumometer is gone, but the shiny ingot seems to have successfully been scanned. With just these mods installed, this is only an issue while scanning through the inventory method using this mod. When throwing the item on the ground to scan it, it functions as intended.

When I run this same test in my modpack however, I do get a crash-report, as my client fully crashes. However it only mentions Thaumcraft: https://gist.github.com/dirtyfargo/30de1f927140c9ee64d4
This time, when re-logging into the world, the Thaumometer is gone again, but the shiny ingot doesn't seem to have successfully been scanned. When testing with my modpack, the issue can be replicated using both methods of scanning (Vanilla Thaumcraft Scanning & Inventory Scanning).

I am unsure whether this IS actually an issue from this mod specifically, but I'm not sure who else to report this one to :P

**Comment by blay09** [comment]
In the first log, it seems a slot was scanned that didn't exist on the server. I'm not sure how that's possible, but just to prevent it in the future I added a range check so it simply ignores those weird things.

The second seems to be some kind of recipe loop or something, I have no idea. You say it happens in Vanilla Thaumcraft Scanning, so it's nothing specific to my mod and there's nothing I can do about it.

**Comment by dirtyfargo** [comment]
Ah alright, weird since I'm playing singleplayer :P  I'm still getting the crash in my modpack with the new version, but as you said, it's not likely to be this mod. Probably one of the 10 other Thaumcraft addons I'm using lol, just no idea which! Thanks anyways though =)

**Comment by blay09** [comment]
For future reference, even singleplayer runs an internal server, so the difference is not all that big.

**Comment by dirtyfargo** [comment]
Oh alright good to know :)
