### ISSUE TITLE
Crash while scanning Ferris Ingots

### ISSUE THREAD

**Issue by MokahTGS** [blay09/TCInventoryScanning#9]
Getting a crash while trying to scan Ferris ingots from Thermal Expansion:

http://pastebin.com/vep8YEKH

**Comment by blay09** [comment]
What version?

**Comment by AnarchySage** [comment]
That crash is related to witching gadgets, turn off transmutation in witching gadgets config file

**Comment by blay09** [comment]
Either way it should already had been fixed in version v1.0.11 which came out in March.
